POST http://localhost:3001/users
Content-Type: application/json

{
        "name": "tks",
        "email": "tks@gmail.com"
}

###

GET http://localhost:3001/users

###

PUT  http://localhost:3000/item/60b8806e97fc0d34477b2aba/quantity/10